# fly.toml app configuration file generated for smart-clinic-api on 2025-08-03T15:59:48+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'smart-clinic-api'
primary_region = 'iad'
console_command = '/code/manage.py shell'

[build]

[deploy]
  release_command = 'python manage.py migrate --noinput'

[env]
  ALLOWED_HOSTS = '.fly.dev'
  CORS_ALLOWED_ORIGINS = 'http://localhost:3000,http://localhost:4200'
  CORS_ALLOW_ALL_ORIGINS = 'true'
  DEBUG = 'false'
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = false
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  # Temporarily disabled health check to get app running
  # [[http_service.checks]]
  #   interval = '60s'
  #   timeout = '10s'
  #   grace_period = '30s'
  #   method = 'GET'
  #   path = '/'

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
