# Generated by Django 5.2.4 on 2025-08-03 10:18

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinic',
            name='phone',
            field=models.CharField(max_length=11, validators=[api.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[api.models.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[api.models.validate_phone_number]),
        ),
    ]
