# Generated by Django 5.2.4 on 2025-08-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_clinic_phone_alter_patient_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorschedule',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='notes',
            field=models.TextField(blank=True, help_text="Optional notes (e.g., 'Holiday', 'Conference')", null=True),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='schedule_type',
            field=models.CharField(choices=[('recurring', 'Recurring Weekly'), ('specific', 'Specific Date')], default='recurring', max_length=10),
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='specific_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule_type', 'recurring')), fields=('doctor', 'day'), name='unique_doctor_recurring_day'),
        ),
        migrations.AddConstraint(
            model_name='doctorschedule',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule_type', 'specific')), fields=('doctor', 'specific_date'), name='unique_doctor_specific_date'),
        ),
    ]
